import React, { useState } from 'react';
import { BookingForm } from '../types';
import { generateGoogleCalendarLink } from '../utils/calendar';
import { saveSubmission } from '../services/supabaseService';

interface BookingModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export const BookingModal: React.FC<BookingModalProps> = ({ isOpen, onClose }) => {
  const [isSubmitted, setIsSubmitted] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [googleCalLink, setGoogleCalLink] = useState('');
  const [formData, setFormData] = useState<BookingForm & { time: string }>({
    name: '',
    email: '',
    phone: '',
    company: '',
    preferred_date: '',
    time: '10:00',
    message: ''
  });

  if (!isOpen) return null;

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsLoading(true);

    try {
      // Validate form data
      if (!formData.name || !formData.email || !formData.phone || !formData.preferred_date || !formData.time) {
        throw new Error('Please fill in all required fields');
      }

      // 1. Construct Event Data
      const bookingDateTime = new Date(`${formData.preferred_date}T${formData.time}`);
      
      // Validate date
      if (isNaN(bookingDateTime.getTime())) {
        throw new Error('Invalid date or time selected');
      }

      const eventDetails = {
        title: `Consultation: ${formData.company || formData.name} with SQ Consulting`,
        description: `Strategy Session.\n\nClient: ${formData.name}\nPhone: ${formData.phone}\nTopic: ${formData.message}\n\nMeeting Link: (Google Meet will be generated by host)`,
        location: 'Google Meet',
        start: bookingDateTime,
        durationMinutes: 45
      };

      // 2. Generate Google Calendar Link
      const link = generateGoogleCalendarLink(eventDetails);
      setGoogleCalLink(link);

      // 3. Save to Supabase
      const submissionResult = await saveSubmission({
        name: formData.name,
        email: formData.email,
        phone: formData.phone,
        subject: "Booking Request",
        message: `Booking Request\n\nCompany: ${formData.company || 'Not specified'}\nPreferred Date: ${formData.preferred_date} at ${formData.time}\n\nMessage: ${formData.message || 'No additional message'}`
      });

      if (!submissionResult.success) {
        throw new Error(submissionResult.message || 'Failed to save booking');
      }

      // 4. Show Success
      setIsSubmitted(true);
    } catch (error: any) {
      console.error('Error submitting booking:', error);
      const errorMessage = error?.message || 'Error submitting booking. Please try again.';
      alert(errorMessage);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="fixed inset-0 z-[9999] flex items-end md:items-center justify-center sm:p-4">
      {/* Backdrop */}
      <div 
        className="absolute inset-0 bg-gray-900/70 backdrop-blur-sm transition-opacity"
        onClick={onClose}
      ></div>

      {/* Modal Content */}
      <div className="relative z-[10000] bg-white w-full max-w-lg overflow-hidden animate-slide-up md:rounded-3xl rounded-t-3xl border-t border-gray-200 md:border md:shadow-2xl h-[90vh] md:h-auto flex flex-col">
        {isSubmitted ? (
          <div className="p-8 md:p-10 text-center flex flex-col items-center animate-fade-in h-full justify-center">
            <div className="w-20 h-20 bg-green-100 rounded-full flex items-center justify-center mb-6 animate-bounce-slow">
              <span className="material-icons text-4xl text-green-600">check_circle</span>
            </div>
            <h3 className="text-2xl font-bold text-gray-900 mb-2">Request Received!</h3>
            <p className="text-gray-600 mb-6 leading-relaxed text-sm">
              We have received your booking request for <strong>{formData.preferred_date} at {formData.time}</strong>. Our team will review and confirm shortly.
            </p>
            
            <a 
              href={googleCalLink}
              target="_blank"
              rel="noopener noreferrer"
              className="bg-white border border-gray-200 text-gray-700 hover:bg-gray-50 px-6 py-3 rounded-xl font-bold transition shadow-sm w-full flex items-center justify-center gap-3 mb-3"
            >
              <img src="https://upload.wikimedia.org/wikipedia/commons/a/a5/Google_Calendar_icon_%282020%29.svg" alt="GCal" className="w-5 h-5" />
              Add to Google Calendar
            </a>

            <button 
              onClick={() => {
                setIsSubmitted(false);
                setFormData({ name: '', email: '', phone: '', company: '', preferred_date: '', time: '10:00', message: '' });
                onClose();
              }}
              className="bg-primary text-white px-8 py-3 rounded-xl font-bold hover:bg-primary-light transition shadow-lg w-full"
            >
              Close
            </button>
          </div>
        ) : (
          <div className="flex flex-col h-full">
             <div className="bg-primary p-6 text-white flex justify-between items-start flex-shrink-0 bg-[url('https://www.transparenttextures.com/patterns/cubes.png')]">
               <div>
                 <h2 className="text-xl md:text-2xl font-bold">Schedule Consultation</h2>
                 <p className="text-purple-200 text-sm mt-1">Free 30-minute growth strategy session.</p>
               </div>
               <button onClick={onClose} className="hover:bg-white/20 p-2 rounded-full transition">
                 <span className="material-icons text-lg">close</span>
               </button>
             </div>
             
             <div className="overflow-y-auto p-6 flex-1">
                <form onSubmit={handleSubmit} className="space-y-4 md:space-y-5">
                <div>
                    <label className="block text-xs font-bold text-gray-500 uppercase tracking-wide mb-1">Full Name</label>
                    <div className="relative">
                        <span className="material-icons absolute left-3 top-2.5 text-gray-400 text-sm">person</span>
                        <input 
                            required
                            type="text" 
                            className="w-full pl-9 pr-4 py-2.5 bg-gray-50 rounded-xl border border-gray-200 focus:bg-white focus:ring-2 focus:ring-primary focus:border-transparent outline-none transition text-base"
                            placeholder="John Doe"
                            value={formData.name}
                            onChange={e => setFormData({...formData, name: e.target.value})}
                        />
                    </div>
                </div>
                <div>
                    <label className="block text-xs font-bold text-gray-500 uppercase tracking-wide mb-1">Work Email</label>
                    <div className="relative">
                        <span className="material-icons absolute left-3 top-2.5 text-gray-400 text-sm">email</span>
                        <input 
                            required
                            type="email" 
                            className="w-full pl-9 pr-4 py-2.5 bg-gray-50 rounded-xl border border-gray-200 focus:bg-white focus:ring-2 focus:ring-primary focus:border-transparent outline-none transition text-base"
                            placeholder="john@company.com"
                            value={formData.email}
                            onChange={e => setFormData({...formData, email: e.target.value})}
                        />
                    </div>
                </div>
                <div>
                    <label className="block text-xs font-bold text-gray-500 uppercase tracking-wide mb-1">Phone Number</label>
                    <div className="relative">
                        <span className="material-icons absolute left-3 top-2.5 text-gray-400 text-sm">phone</span>
                        <input 
                            required
                            type="tel" 
                            className="w-full pl-9 pr-4 py-2.5 bg-gray-50 rounded-xl border border-gray-200 focus:bg-white focus:ring-2 focus:ring-primary focus:border-transparent outline-none transition text-base"
                            placeholder="+234 XXX XXX XXXX"
                            value={formData.phone}
                            onChange={e => setFormData({...formData, phone: e.target.value})}
                        />
                    </div>
                </div>
                <div className="grid grid-cols-2 gap-4">
                    <div>
                        <label className="block text-xs font-bold text-gray-500 uppercase tracking-wide mb-1">Date</label>
                         <div className="relative">
                            <input 
                                required
                                type="date" 
                                className="w-full px-4 py-2.5 bg-gray-50 rounded-xl border border-gray-200 focus:bg-white focus:ring-2 focus:ring-primary focus:border-transparent outline-none transition text-sm text-gray-600 appearance-none"
                                value={formData.preferred_date}
                                onChange={e => setFormData({...formData, preferred_date: e.target.value})}
                            />
                        </div>
                    </div>
                    <div>
                        <label className="block text-xs font-bold text-gray-500 uppercase tracking-wide mb-1">Time</label>
                         <div className="relative">
                            <input 
                                required
                                type="time" 
                                className="w-full px-4 py-2.5 bg-gray-50 rounded-xl border border-gray-200 focus:bg-white focus:ring-2 focus:ring-primary focus:border-transparent outline-none transition text-sm text-gray-600 appearance-none"
                                value={formData.time}
                                onChange={e => setFormData({...formData, time: e.target.value})}
                            />
                        </div>
                    </div>
                </div>
                <div>
                    <label className="block text-xs font-bold text-gray-500 uppercase tracking-wide mb-1">Company (Optional)</label>
                        <div className="relative">
                        <span className="material-icons absolute left-3 top-2.5 text-gray-400 text-sm">business</span>
                        <input 
                            type="text" 
                            className="w-full pl-9 pr-4 py-2.5 bg-gray-50 rounded-xl border border-gray-200 focus:bg-white focus:ring-2 focus:ring-primary focus:border-transparent outline-none transition text-base"
                            placeholder="Acme Inc"
                            value={formData.company}
                            onChange={e => setFormData({...formData, company: e.target.value})}
                        />
                    </div>
                </div>
                <div>
                    <label className="block text-xs font-bold text-gray-500 uppercase tracking-wide mb-1">Project Details</label>
                    <textarea 
                        rows={3}
                        className="w-full px-4 py-3 bg-gray-50 rounded-xl border border-gray-200 focus:bg-white focus:ring-2 focus:ring-primary focus:border-transparent outline-none transition resize-none text-base"
                        placeholder="Briefly describe your goals..."
                        value={formData.message}
                        onChange={e => setFormData({...formData, message: e.target.value})}
                    />
                </div>
                
                <button 
                    type="submit"
                    disabled={isLoading}
                    className="w-full bg-secondary hover:bg-orange-600 text-white font-bold py-3.5 rounded-xl shadow-lg transform active:scale-95 transition duration-200 flex items-center justify-center gap-2 disabled:opacity-70 disabled:cursor-not-allowed mb-safe"
                >
                    {isLoading ? (
                        <>
                           <svg className="animate-spin h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                              <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                              <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                            </svg>
                            Processing...
                        </>
                    ) : (
                        <>
                            Confirm Appointment
                            <span className="material-icons text-sm">calendar_month</span>
                        </>
                    )}
                </button>
                </form>
             </div>
          </div>
        )}
      </div>
    </div>
  );
};